jobs:
  - job: ${{ parameters.name }}
    displayName: CI build for ${{ parameters.displayName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - task: UseDotNet@2
        displayName: Use .NET Core SDK ${{ parameters.dotNetCoreVersion }}
        inputs:
          version: ${{ parameters.dotNetCoreVersion }}

      - powershell: dotnet tool install --tool-path ./tools --version ${{ parameters.cakeVersion }} Cake.Tool
        displayName: Setup prerequisites

      - powershell: ./tools/dotnet-cake --target=Restore-NuGet-Packages
        displayName: Prepare

      - powershell: ./tools/dotnet-cake --target=Build
        displayName: Build

      - powershell: ./tools/dotnet-cake --target=Test --test-filter="${{ parameters.testFilter }}"
        displayName: Tests

      - powershell: Get-ChildItem -Path **/*.log -Recurse | % { Get-Content -Path $_.FullName }
        displayName: Logs
