global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Threading.Tasks;
global using Amazon.DynamoDBv2;
global using Amazon.DynamoDBv2.Model;
global using DotNet.Testcontainers.Commons;
global using Xunit;