version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - '*'
  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: Microsoft.Bcl.*
        update-types:
          - version-update:semver-major
      - dependency-name: Microsoft.Extensions.*
        update-types:
          - version-update:semver-major
    groups:
      nuget-patch-minor:
        update-types:
          - minor
          - patch
      nuget-major:
        update-types:
          - major
