version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github_actions
    groups:
      actions:
        patterns:
          - '*'
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - nuget
    ignore:
      - dependency-name: '*'
        versions:
          - '>= 0'
