# NOTE: The tag "v{Major}.{Minor}" must match the exact version of the
# Microsoft.Playwright package specified in Directory.Packages.props.
FROM mcr.microsoft.com/playwright:v1.62.1@sha256:dcc5531e97840b9b5e794f2814476b21571c5124a3fca2267d73041f56e7580e