# NOTE: The tag "v{Major}.{Minor}" must match the exact version of the
# Microsoft.Playwright package specified in Directory.Packages.props.
FROM mcr.microsoft.com/playwright:v1.55.1@sha256:2f29369043d81d6d69a815ceb80760f55e85f5020371ad06a4d996f18503ad1c