global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using Docker.DotNet.Models;
global using DotNet.Testcontainers.Builders;
global using DotNet.Testcontainers.Commons;
global using DotNet.Testcontainers.Configurations;
global using DotNet.Testcontainers.Containers;
global using Xunit;