global using System.Data;
global using System.Data.Common;
global using System.Threading.Tasks;
global using DotNet.Testcontainers.Commons;
global using JetBrains.Annotations;
global using Oracle.ManagedDataAccess.Client;
global using Testcontainers.Xunit;
global using Xunit;
global using Xunit.Abstractions;