name: Formatting check

on:
  workflow_dispatch:
  pull_request:

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: CSharpier Linter
        uses: guibranco/github-csharpier-linter-action@v1.0.5
