name: OpenSSF Scorecard

on:
  push:
    branches: [ develop ]
    paths-ignore: [ 'docs/**', 'examples/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  analyze:
    permissions:
      contents: read
      id-token: write
      security-events: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
          persist-credentials: false

      - name: Perform OpenSSF Scorecard Analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif

      - name: Upload SARIF Result
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload SARIF Result to CodeQL Code Scanning
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: results.sarif
